### ISSUE TITLE
Trigger angry Lattner when using `!` in Swift

### ISSUE THREAD

**Issue by AliSoftware** [orta/You-Can-Do-It#3]
We should definitely enhance this plugin to trigger this animation on Xcode's dock icon every time one use `!` in their Swift code :joy: 

https://twitter.com/simjp/status/684779231117619200

**Comment by Jxrgxn** [comment]
I'm on it!!

**Comment by orta** [comment]
You should _definitely_ do this, but do it in a fork and ship it separately. 

I totally agree with the concept, but it doesn't mesh well with the _idea_ of "you can do it" - which is, well, you can do it. It's about _encouragement_, not a reminder that what you're doing isn't always best practice.

**Comment by Jxrgxn** [comment]
Absolutely. As someone who prefers positive encouragement over droll,
typical, developer sarcasm I'm 100% with you.
ᐧ

**Comment by orta** [comment]
Closing as this is another project :+1:
